package org.data.wrangler.files;

import java.util.Locale;

/** Builds DuckDB read expressions and starter queries (with format-specific tips) for data files. NetBeans-free, unit-tested. */
public final class QueryTemplates {

 private QueryTemplates() {}

 enum Kind { CSV, TSV, PARQUET, JSON, XLSX, OTHER }

 static Kind kindOf(String lower) {
 if (lower.endsWith(".parquet") || lower.endsWith(".pq")) return Kind.PARQUET;
 if (lower.endsWith(".json") || lower.endsWith(".jsonl") || lower.endsWith(".ndjson") || lower.endsWith(".jsonlines")) return Kind.JSON;
 if (lower.endsWith(".xlsx") || lower.endsWith(".xlsm")) return Kind.XLSX;
 if (lower.endsWith(".tsv")) return Kind.TSV;
 if (lower.endsWith(".csv.gz") || lower.endsWith(".csv") || lower.endsWith(".txt")) return Kind.CSV;
 return Kind.OTHER;
    }

    /** A FROM-able DuckDB expression that reads the file, chosen by extension. */
 public static String readerFor(String absolutePath) {
        String p = quote(absolutePath);
 return switch (kindOf(absolutePath.toLowerCase(Locale.ROOT))) {
 case PARQUET -> "read_parquet('" + p + "')";
 case JSON -> isJsonLines(absolutePath)
                    ? "read_json('" + p + "', format = 'newline_delimited')"
                    : "read_json_auto('" + p + "')";
 case XLSX -> "read_xlsx('" + p + "')";
 case TSV -> "read_csv('" + p + "', header = true, delim = '\\t', auto_detect = true)";
 case CSV -> "read_csv('" + p + "', header = true, auto_detect = true)";
 case OTHER -> "'" + p + "'"; // let DuckDB's replacement scan guess
        };
    }

 static boolean isJsonLines(String path) {
        String l = path.toLowerCase(Locale.ROOT);
 return l.endsWith(".jsonl") || l.endsWith(".ndjson") || l.endsWith(".jsonlines");
    }

 static String quote(String absolutePath) {
 return absolutePath.replace('\\', '/').replace("'", "''");
    }

 public static String forFile(String absolutePath) {
        String reader = readerFor(absolutePath);
        String p = quote(absolutePath);
        StringBuilder sb = new StringBuilder();
 sb.append("-- Generated by NetBeans DuckDB support. Run with Ctrl+Shift+E; select text to run only that.\n");
 sb.append("SELECT *\nFROM ").append(reader).append("\nLIMIT 100;\n\n");
 sb.append("-- Things to try (uncomment one; replace column names with yours):\n");
 sb.append("-- DESCRIBE SELECT * FROM ").append(reader).append(";                       -- columns and inferred types\n");
 sb.append("-- SUMMARIZE ").append(reader).append(";                                   -- min/max/avg/nulls per column\n");
 sb.append("-- SELECT count(*) FROM ").append(reader).append(";\n");
 sb.append("-- SELECT some_col, count(*) AS n FROM ").append(reader).append(" GROUP BY ALL ORDER BY n DESC LIMIT 10;\n");
 switch (kindOf(absolutePath.toLowerCase(Locale.ROOT))) {
 case CSV, TSV -> {
 sb.append("-- CSV specifics:\n");
 sb.append("-- SELECT * FROM sniff_csv('").append(p).append("');                          -- what the sniffer decided (delimiter, quote, types)\n");
 sb.append("-- SELECT * FROM read_csv('").append(p).append("', all_varchar = true) LIMIT 20;   -- raw text, no type guessing\n");
 sb.append("-- SELECT * FROM read_csv('").append(p).append("', types = {'some_col': 'DATE'});   -- override one column's type\n");
 sb.append("-- SELECT * FROM read_csv('").append(p).append("', ignore_errors = true);          -- skip rows that fail to parse\n");
 sb.append("-- CREATE OR REPLACE TABLE t AS SELECT * FROM ").append(reader).append(";      -- load into a table\n");
 sb.append("-- COPY (SELECT * FROM ").append(reader).append(") TO 'out.parquet' (FORMAT parquet);\n");
            }
 case PARQUET -> {
 sb.append("-- Parquet specifics:\n");
 sb.append("-- SELECT * FROM parquet_schema('").append(p).append("');                       -- columns, physical types, repetition\n");
 sb.append("-- SELECT row_group_id, num_rows, total_compressed_size FROM parquet_metadata('").append(p).append("');\n");
 sb.append("-- SELECT path_in_schema, stats_min, stats_max FROM parquet_metadata('").append(p).append("');   -- row-group statistics\n");
 sb.append("-- SELECT * FROM read_parquet('").append(p.replaceAll("[^/]+$", "*.parquet")).append("', filename = true);   -- all files in the folder\n");
 sb.append("-- SELECT some_list[1], len(some_list) FROM ").append(reader).append(";           -- LIST columns\n");
 sb.append("-- SELECT some_struct.field FROM ").append(reader).append(";                     -- STRUCT columns\n");
            }
 case JSON -> {
 sb.append("-- JSON specifics:\n");
 sb.append("-- SELECT json_structure(json) FROM read_json_objects('").append(p).append("') LIMIT 1;   -- the shape DuckDB sees\n");
 sb.append("-- SELECT * FROM read_json('").append(p).append("', format = 'newline_delimited');   -- force NDJSON\n");
 sb.append("-- SELECT some_object.field FROM ").append(reader).append(";                    -- nested object -> STRUCT\n");
 sb.append("-- SELECT unnest(some_array) FROM ").append(reader).append(";                   -- explode an array\n");
 sb.append("-- SELECT id, unnest(items, recursive := true) FROM ").append(reader).append(";  -- array of objects -> columns\n");
 sb.append("-- SELECT json_extract(to_json(x), '$.field') FROM ").append(reader).append(" x;  -- JSON path on any row\n");
 sb.append("-- COPY (SELECT * FROM ").append(reader).append(") TO 'out.parquet' (FORMAT parquet);  -- keeps nesting\n");
            }
 case XLSX -> {
 sb.append("-- Excel specifics (read_xlsx from the excel extension; first sheet by default):\n");
 sb.append("-- SELECT * FROM read_xlsx('").append(p).append("', sheet = 'Sheet2');           -- another sheet\n");
 sb.append("-- SELECT * FROM read_xlsx('").append(p).append("', header = false);            -- row 1 as data, columns A, B, C...\n");
 sb.append("-- SELECT * FROM read_xlsx('").append(p).append("', range = 'A1:D20');          -- a cell range\n");
 sb.append("-- SELECT * FROM read_xlsx('").append(p).append("', all_varchar = true);        -- no type guessing\n");
 sb.append("-- SELECT * FROM read_xlsx('").append(p).append("', stop_at_empty = false);     -- keep reading past blank rows\n");
 sb.append("-- Join two sheets:\n");
 sb.append("-- SELECT o.*, p.category FROM read_xlsx('").append(p).append("', sheet = 'orders') o\n");
 sb.append("--   JOIN read_xlsx('").append(p).append("', sheet = 'products') p USING (product);\n");
 sb.append("-- Pivot a sheet: PIVOT read_xlsx('").append(p).append("') ON some_col USING sum(some_value);\n");
 sb.append("-- Write a sheet: COPY (SELECT ...) TO 'out.xlsx' (FORMAT xlsx, HEADER true, SHEET 'Result');\n");
            }
 case OTHER -> { }
        }
 return sb.toString();
    }
}
